/**
 * Post-build prerender step.
 *
 * The app is a client-rendered SPA, so `vite build` emits a single HTML shell
 * whose <title>/<meta> describe the Arabic home page only. Crawlers that do not
 * execute JavaScript (WhatsApp, X, LinkedIn, Facebook, and basic indexers) would
 * therefore show home-page metadata for every URL in sitemap.xml.
 *
 * This script writes one static HTML file per indexable route, with the correct
 * <html lang/dir>, <title>, description, robots, canonical, hreflang alternates,
 * Open Graph / Twitter tags and JSON-LD already present in the markup.
 *
 * Head values are produced by the application's own modules
 * (src/lib/seo.ts, src/lib/schema.ts) — never re-implemented here — so the
 * prerendered markup and the runtime markup cannot drift. The subsequent
 * snapshot step captures the browser-rendered body into the same route files.
 */
import "./lib/register-alias.mjs";

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const { EM } = await import("@/data/em.js");
const { buildSeo, absUrl } = await import("@/lib/seo.ts");
const { buildJsonLd } = await import("@/lib/schema.ts");
const { withLang } = await import("@/lib/i18n-path.ts");

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");
const SHELL = join(DIST, "index.html");
const LANGS = ["ar", "en"];

if (!existsSync(SHELL)) {
  console.error("[prerender] dist/index.html not found — run `vite build` first.");
  process.exit(1);
}

const shell = readFileSync(SHELL, "utf8");

/* ------------------------------------------------------------------ routes */

const PAGE_PATHS = ["", "about", "consulting", "execution", "sectors", "cases", "insights", "contact"];

/** Indexable paths, language-neutral. Order matches public/sitemap.xml. */
function routePaths() {
  const paths = PAGE_PATHS.map((page) => (page ? `/${page}` : "/"));
  for (const item of EM.CASES) paths.push(`/cases/${item.id}`);
  for (const item of EM.INSIGHTS) paths.push(`/insights/${item.id}`);
  return paths;
}

const paths = routePaths();

/* ---------------------------------------------------------------- escaping */

const escapeText = (value) => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escapeAttr = (value) => escapeText(value).replace(/"/g, "&quot;");
const escapeJsonLd = (value) => value.replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");

/* --------------------------------------------------------------- head HTML */

function metaTag(attrs) {
  const parts = Object.entries(attrs)
    .filter(([, value]) => value !== undefined && value !== null)
    .map(([key, value]) => `${key}="${escapeAttr(value)}"`);
  return `<meta ${parts.join(" ")}>`;
}

function linkTag(attrs) {
  const parts = Object.entries(attrs)
    .filter(([, value]) => value !== undefined && value !== null)
    .map(([key, value]) => `${key}="${escapeAttr(value)}"`);
  return `<link ${parts.join(" ")}>`;
}

function headBlock(path, lang) {
  const seo = buildSeo(path, lang);
  const jsonLd = JSON.stringify(buildJsonLd(path, lang));
  const canonical = absUrl(seo.canonicalPath);
  const ogImage = absUrl(seo.ogImage);
  const locale = lang === "ar" ? "ar_AE" : "en_GB";
  const alternateLocale = lang === "ar" ? "en_GB" : "ar_AE";

  return [
    `<!-- prerendered head for ${withLang(path, lang)} — generated by scripts/prerender.mjs -->`,
    `<title>${escapeText(seo.title)}</title>`,
    metaTag({ name: "description", content: seo.description }),
    metaTag({ name: "robots", content: seo.noindex ? "noindex, nofollow" : "index, follow" }),
    linkTag({ rel: "canonical", href: canonical }),
    linkTag({ rel: "alternate", hreflang: "ar", href: absUrl(withLang(path, "ar")) }),
    linkTag({ rel: "alternate", hreflang: "en", href: absUrl(withLang(path, "en")) }),
    linkTag({ rel: "alternate", hreflang: "x-default", href: absUrl(withLang(path, "ar")) }),
    metaTag({ property: "og:title", content: seo.ogTitle || seo.title }),
    metaTag({ property: "og:description", content: seo.ogDescription || seo.description }),
    metaTag({ property: "og:type", content: seo.ogType }),
    metaTag({ property: "og:url", content: canonical }),
    metaTag({ property: "og:image", content: ogImage }),
    metaTag({ property: "og:image:alt", content: seo.ogImageAlt }),
    metaTag({ property: "og:locale", content: locale }),
    metaTag({ property: "og:locale:alternate", content: alternateLocale }),
    metaTag({ property: "og:site_name", content: "Elite Maison" }),
    metaTag({ name: "twitter:card", content: "summary_large_image" }),
    metaTag({ name: "twitter:title", content: seo.title }),
    metaTag({ name: "twitter:description", content: seo.description }),
    metaTag({ name: "twitter:image", content: ogImage }),
    `<script type="application/ld+json" id="em-jsonld">${escapeJsonLd(jsonLd)}</script>`
  ].join("\n  ");
}

function renderRoute(path, lang) {
  const dir = lang === "ar" ? "rtl" : "ltr";
  return shell
    .replace(/<html[^>]*>/i, `<html lang="${lang}" dir="${dir}">`)
    .replace(/<title>[\s\S]*?<\/title>\s*/i, "")
    .replace(/<meta\s+name="description"[^>]*>\s*/i, "")
    .replace(/<\/head>/i, `  ${headBlock(path, lang)}\n</head>`);
}

/* ------------------------------------------------------------------ output */

let written = 0;
for (const path of paths) {
  for (const lang of LANGS) {
    const urlPath = withLang(path, lang).replace(/^\//, "");
    const target = join(DIST, urlPath, "index.html");
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, renderRoute(path, lang), "utf8");
    written += 1;
  }
}

// The generated 404 is served directly by server.mjs with HTTP 404.
// It must never be indexable and must not canonicalize anywhere.
const notFoundShell = shell
  .replace(/<\/head>/i, '  <meta name="robots" content="noindex, nofollow">\n</head>')
  .replace(
    /<noscript>/i,
    '<noscript>\n    <main id="main" class="page shell"><section class="section"><h1>الصفحة التي تبحث عنها غير موجودة.</h1><p>The page you are looking for does not exist.</p><p><a href="/ar">العودة إلى الرئيسية</a> · <a href="/en">Back to home</a></p></section></main>'
  );
writeFileSync(join(DIST, "404.html"), notFoundShell, "utf8");

// The bare `/` shell only boots the client redirect to /ar or /en. Point
// crawlers at the default-language canonical instead of leaving it unspecified.
{
  const rootShell = readFileSync(SHELL, "utf8");
  const rootHead = [
    linkTag({ rel: "canonical", href: absUrl(withLang("/", "ar")) }),
    linkTag({ rel: "alternate", hreflang: "ar", href: absUrl(withLang("/", "ar")) }),
    linkTag({ rel: "alternate", hreflang: "en", href: absUrl(withLang("/", "en")) }),
    linkTag({ rel: "alternate", hreflang: "x-default", href: absUrl(withLang("/", "ar")) })
  ].join("\n  ");
  writeFileSync(SHELL, rootShell.replace(/<\/head>/i, `  ${rootHead}\n</head>`), "utf8");
}

/* ------------------------------------------------------------------ robots */

// Indexability governance: the release decision is now granted by the owner.
// Production builds run with EM_RELEASE_APPROVED=1 via .env.production, so
// crawler access is open. Named client claims become public-indexable only
// when publicationApproved is true and anonymizeCases is false.
// Markup itself remains fully testable in the dist files.
{
  const approved = process.env.EM_RELEASE_APPROVED === "1"
    && EM.CONFIG.publicationApproved !== false
    && !EM.CONFIG.anonymizeCases;
  const robots = approved
    ? [
      "# Elite Maison — production robots (publication approved).",
      "# Generated by scripts/prerender.mjs — do not hand-edit dist output.",
      "",
      "# OAI-SearchBot powers AI-search discoverability; keep it allowed.",
      "User-agent: OAI-SearchBot",
      "Allow: /",
      "",
      "# GPTBot trains models; it is not needed for search visibility.",
      "User-agent: GPTBot",
      "Disallow: /",
      "",
      "User-agent: *",
      "Allow: /",
      "",
      "# Contact wizard step is a UI state, not a page.",
      "Disallow: /*?*step=",
      "Disallow: /*?step=",
      "",
      `Sitemap: ${absUrl("/sitemap.xml")}`,
      ""
    ].join("\n")
    : [
      "# Elite Maison — PRE-RELEASE robots.",
      "# This block is only reached when EM_RELEASE_APPROVED is absent or",
      "# publicationApproved is false / anonymizeCases is true.",
      "# Production builds use EM_RELEASE_APPROVED=1 via .env.production.",
      "",
      "User-agent: *",
      "Disallow: /",
      ""
    ].join("\n");
  writeFileSync(join(DIST, "robots.txt"), robots, "utf8");
  console.log(`[prerender] robots.txt: ${approved ? "production (crawling open)" : "PRE-RELEASE (crawling closed)"}`);
}

/* ----------------------------------------------------------------- sitemap */

function sitemapXml() {
  const entries = [];
  for (const path of paths) {
    for (const lang of LANGS) {
      const url = absUrl(withLang(path, lang));
      entries.push(
        [
          "  <url>",
          `    <loc>${escapeText(url)}</loc>`,
          `    <xhtml:link rel="alternate" hreflang="ar" href="${escapeAttr(absUrl(withLang(path, "ar")))}"/>`,
          `    <xhtml:link rel="alternate" hreflang="en" href="${escapeAttr(absUrl(withLang(path, "en")))}"/>`,
          `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeAttr(absUrl(withLang(path, "ar")))}"/>`,
          "  </url>"
        ].join("\n")
      );
    }
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    entries.join("\n"),
    "</urlset>",
    ""
  ].join("\n");
}

const generatedSitemap = sitemapXml();
writeFileSync(join(DIST, "sitemap.xml"), generatedSitemap, "utf8");

const normalizeEol = (value) => value.replace(/\r\n/g, "\n");
const committedSitemapPath = join(ROOT, "public", "sitemap.xml");
if (existsSync(committedSitemapPath) && normalizeEol(readFileSync(committedSitemapPath, "utf8")) !== normalizeEol(generatedSitemap)) {
  console.warn(
    "[prerender] WARNING: public/sitemap.xml differs from the routes derived from src/data/em.js.\n" +
    "            dist/sitemap.xml is authoritative for this build. Update public/sitemap.xml to match."
  );
}

/* ------------------------------------------------------------------ report */

const publicCases = EM.CONFIG.publicationApproved !== false && !EM.CONFIG.anonymizeCases
  ? EM.CASES.length
  : 0;

console.log(`[prerender] ${written} static pages across ${paths.length} routes × ${LANGS.length} languages`);
console.log(`[prerender] wrote dist/404.html and dist/sitemap.xml (${paths.length * LANGS.length} URLs)`);
if (publicCases) {
  console.log(`[prerender] NOTE: publicationApproved=true — ${publicCases} named client cases are indexable.`);
  console.log("            Run `npm run check:release` before deploying to a public origin.");
}
